Melodic devel
bosch-ros-pkg/photo pull request #4
Opened 2018-11-13 18:28 UTC by romainreignier

Add some fixes to use on Melodic with Ubuntu bionic, so a more recent version of gphoto2.
Plus various fixes.

I think a melodic-devel branch should be created to merge this PR.

2019-03-04 07:21 UTC, dejanpan commented
@iluetkeb is anyone still watching this repo and can review this PR?

2019-03-04 18:53 UTC, lorenzoriano commented
I don't know who's in charge of this whole organization.. @proan  do you know who is in the robotics team?

2019-03-05 11:54 UTC, ralph-lange commented
@romainreignier, thank you very much for contributing to this repo. As indicated in the previous comments by @dejanpan and @lorenzoriano, the maintenance of this repo is currently unclear. I'll check this with my colleagues and then come back to you in the next days.

2019-03-11 18:24 UTC, Karsten1987 requested changes
@romainreignier thanks for the patch. I am requesting changes because of the segmentation fault issue when no cameras are available. 

I just uploaded a `melodic-devel` branch. Please feel free to rebase this PR onto the new melodic branch.

2019-03-11 18:24 UTC, Karsten1987 commented on CMakeLists.txt
> +add_library(photo
why is this change necessary? Just by looking at the sources files used, it would make sense to me to refer to `photo2` as it's supposingly using `libphoto2` and thus prevent any name/symbol clashing with an existing `photo(1)` library.

2019-03-11 18:24 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
> +  const char *name, *value;
This chance leads to segmentation faults if errors are not correctly treated. Or better, it is crashing down in line `133` when you try printing the values. I ran into these problems when trying to run it in a docker container without any camera access.

proposed fix:
```
  const char *name = NULL;
  const char *value = NULL;

  gp_list_get_name( list->getCameraList(), n, &name);
  if (name == NULL) {
    photo_reporter::error( "could not get name of camera" );
    return false;
  }
  gp_list_get_value( list->getCameraList(), n, &value);
  if (value == NULL) {
    photo_reporter::error( "could not get value of camera" );
    return false;
  }
```

2019-03-11 18:24 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
> +bool photo_camera::photo_camera_check_toggle_value( std::string value_in, int* value_out )
Can you elaborate on why you want to break the API here?

2019-03-11 19:15 UTC, proan commented on include/photo/photo_reporter.hpp
> +  void contextError( GPContext* context, const char* format, void* data );
There's a mismatch between the variable name here in the declaration with the definition in photo_reporter.cpp:58. Please replace the `const char* format` here with `const char *error_string`

2019-03-11 19:17 UTC, proan commented on include/photo/photo_reporter.hpp
> +  void contextStatus( GPContext* context, const char* format, void* data );
Similar to the line above, replace `const char* format` with `const char *status_string`

2019-03-11 22:42 UTC, romainreignier commented on CMakeLists.txt
> +add_library(photo
You are right, there is no good reason.
I think I had a bad configuration that prevented me to use the lib in another package.
I will remove this useless and misleading commit.

2019-03-11 22:43 UTC, romainreignier commented on include/photo/photo_reporter.hpp
> +  void contextError( GPContext* context, const char* format, void* data );
Sure, thanks.

2019-03-11 22:43 UTC, romainreignier commented on include/photo/photo_reporter.hpp
> +  void contextStatus( GPContext* context, const char* format, void* data );
No problem

2019-03-11 22:45 UTC, romainreignier commented on src/libphoto2/photo_camera.cpp
> +  const char *name, *value;
I am not sure that it is the whitespace removal that cause the segfault ;)
But yes, sure, I will initialize them to `NULL`.

2019-03-11 22:57 UTC, romainreignier commented on src/libphoto2/photo_camera.cpp
> +bool photo_camera::photo_camera_check_toggle_value( std::string value_in, int* value_out )
Yes, sure.

I know this particular change seem like a non-sense.

But the reason is line 339. The variable `tog` was declared as a `bool` but the method `gp_widget_set_value` of libgphoto2 takes a `const void*` that is then casted to an `int` [here](https://github.com/gphoto/libgphoto2/blob/1f1394b79901ac5412bf94fca6694ba8cc1591bd/libgphoto2/gphoto2-widget.c#L413) (there is no `bool` in ANSI C). But on my architecture (x86_64), a `bool` in C++ takes less space in memory than an `int` so depending of the state of the memory, the `bool` casted to a larger `int` could be different than `0`, so evaluated as `true`.
So we have to stay with an `int` in the C++ wrapper.
Because `photo_camera_check_toggle_value()` takes `tog` as argument, I have found simpler to keep its type so `int`.
I hope I was clear. If you have any idea to make the code clearer, I am OK to change.

2019-03-11 23:19 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
> +  const char *name, *value;
it's certainly not the whitespace removal. Ideally we should backport this fix to `hydro-devel` as well. But given that it's long EOL I think addressing the fix for melodic is sufficient.

2019-03-11 23:21 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
> +bool photo_camera::photo_camera_check_toggle_value( std::string value_in, int* value_out )
thanks for the explanation. That sounds absolutely correct.

2019-03-11 23:58 UTC, romainreignier commented on src/libphoto2/photo_camera.cpp
>   * boost::iequals( s1, s2 );
I have a patch to use `boost::iequals` as the comment requested but maybe it's better to wait for this PR to be merged first?

2019-03-12 00:18 UTC, Karsten1987 approved these changes
a few nitpicks, but looks good to me.
Thanks for iterating over this patch.

2019-03-12 00:18 UTC, Karsten1987 commented on include/photo/photo_camera.hpp
> +  int photo_camera_find_widget_by_name( std::string param, CameraWidget **child,
```suggestion
  int photo_camera_find_widget_by_name( const std::string& param, CameraWidget **child,
```

2019-03-12 00:18 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
>    gp_list_get_name( list->getCameraList(), n, &name);
```suggestion
  gp_list_get_name( list->getCameraList(), n, &name );
```

2019-03-12 00:18 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
>    gp_list_get_value( list->getCameraList(), n, &value);
```suggestion
  gp_list_get_value( list->getCameraList(), n, &value );
```

2019-03-12 00:18 UTC, Karsten1987 commented on src/libphoto2/photo_camera.cpp
> +int photo_camera::photo_camera_find_widget_by_name( std::string name, CameraWidget **child,
```suggestion
int photo_camera::photo_camera_find_widget_by_name( const std::string& name, CameraWidget **child,
```

2019-03-13 02:13 UTC, Karsten1987 commented
@romainreignier if you could accept the latest suggestions, I am happy to accept the PR and re-release the package in melodic.

2019-03-13 10:50 UTC, romainreignier commented on include/photo/photo_camera.hpp
> +  int photo_camera_find_widget_by_name( std::string param, CameraWidget **child,
This one is not that easy because the param is modified in the method.

See here for example:

https://github.com/romainreignier/photo/blob/c94034a08bc6298650cb03a99d08f5097172c43b/src/libphoto2/photo_camera.cpp#L199

If you prefer I can create a local variable. But in any case a copy is needed.

2019-03-13 16:15 UTC, merged

2019-03-13 16:15 UTC, Karsten1987 commented
@romainreignier for iterating over this.